name: 'Gitflow version'
description: 'Generate next version based on gitflow style.'
outputs:
  inc:
    description: "Increment"
    value: ${{ steps.get-inc-and-preid.outputs.inc }}
  preid:
    description: "Pre ID"
    value: ${{ steps.get-inc-and-preid.outputs.preid }}
runs:
  using: "composite"
  steps:     
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install semver
      run: npm install -g semver
      shell: bash

    - name: Generate inc and preid
      id: get-inc-and-preid
      run: |
        # Feature -> Develop
        if ${{ startsWith(github.head_ref, 'feature') && github.ref == 'develop' }};
        then
          # Breaking change
          if ${{ contains(github.event.pull_request.labels.*.name, 'breaking') }};
          then
            echo "::set-output name=inc::premajor"
            echo "::set-output name=preid::alpha"
          else
            echo "::set-output name=inc::preminor"
            echo "::set-output name=preid::alpha"
          fi
        # Create release branch
        elif ${{ github.head_ref == '' && github.ref == 'refs/heads/release/' }}
        then
          echo "::set-output name=inc::prerelease"
          echo "::set-output name=preid::rc"
        # Release -> Develop (Bugfixing on release candinate)
        elif ${{ startsWith(github.head_ref, 'release') && github.ref == 'develop' }}
        then
          echo "::set-output name=inc::prepatch"
          echo "::set-output name=preid::alpha"
        # Hotfix -> Develop (hotfix from main)
        elif ${{ startsWith(github.head_ref, 'hotfix') && github.ref == 'develop' }};
        then
          echo "::set-output name=inc::prepatch"
          echo "::set-output name=preid::alpha"
        # Bugfix -> Release
        elif ${{ startsWith(github.head_ref, 'bugfix') && github.ref == 'refs/heads/release/' }}
        then
          echo "::set-output name=inc::prepatch"
          echo "::set-output name=preid::rc"
        # Release -> Main
        elif ${{ startsWith(github.head_ref, 'release') && github.ref == 'main' }}
        then
          echo "::set-output name=inc::stable"
          echo "::set-output name=preid::"
        # Hotfix -> Main
        elif ${{ startsWith(github.head_ref, 'hotfix') && github.ref == 'main' }};
        then
          echo "::set-output name=inc::prepatch"
          echo "::set-output name=preid::"
        fi
      shell: bash

    - name: Update version
      run: |
        VERSION=`cat ./version.txt`
        INC=${{ steps.get-inc-and-preid.outputs.inc }}
        PREID=${{ steps.get-inc-and-preid.outputs.preid }}
        semver $VERSION -i $INC --preid $PREID > ./version.txt
      shell: bash

    - name: Commit changes
      run: |
        VERSION=`cat ./version.txt`
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git config --local user.name 'github-actions[bot]'
        git commit -am "Bump version to $VERSION"
        git push
      shell: bash
